[package]
name = "poloto"
version = "1.5.2"
authors = ["Ken <kenakioreed@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/tiby312/poloto"
description = "Simple 2D plotting library that outputs SVG and can be styled using CSS"
keywords = ["svg", "css","plot","chart","plotting"]
readme = "README.md"
include = ["src/**/*", "LICENSE-MIT", "README.md"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tagger = "0.7"